GerenciamentoCinema/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using GerenciamentoCinema.Models;

namespace GerenciamentoCinema.Controllers {
	public class HomeController : Controller {
		public ActionResult Index() {
			ViewBag.Title = "Home";
			if (Convert.ToBoolean(Session["auth"])) {
				return RedirectToAction("Home", "Home");
			} else {
				return View();
			}

			
		}
		public ActionResult Home() {
			if (!Convert.ToBoolean(Session["auth"])) {
				return RedirectToAction("Index", "Home");
			} else {
				return View();
			}
		}

		
		public ActionResult Login() {
			ViewBag.Title = "Login";
			if (Convert.ToBoolean(Session["auth"])) {
				return RedirectToAction("Home", "Home");
			} else {
				return View();
			}
		}

		[HttpPost]
		public ActionResult Login(UserModel login) {
			if (!ModelState.IsValid) {
				return View(login);
			}

			var username = UserModel.isValidUser(login.user, login.password); 
			
			if (username != "") {
				Session.Add("auth_user_name", username);
				Session.Add("auth", true);
				Session.Timeout = 60;
				return RedirectToAction("Index", "Home");				
			} else {
				ModelState.AddModelError("", "Login inválido.");
				Session.Add("auth", false);
			}

			return View(login);
		}

		public ActionResult LogOff() {
			Session.Add("auth", false);
			return RedirectToAction("Index", "Home");
		}
	}
}

GerenciamentoCinema/Controllers/MigrationsController.cs
using System;
using System.Web.Mvc;
using System.Text;
using GerenciamentoCinema.Properties;
using GerenciamentoCinema.Models;

namespace GerenciamentoCinema.Controllers {
	public class MigrationsController : Controller {

		public ActionResult Index() {

			return View();
		}

		public string checkAuth(string password_migration) {
			if (password_migration == "admin") {
				return "";
			} else {
				return "senha incorreta";
			}
		}


		[HttpPost]
		public JsonResult check() {
			return Json(MigrationsModel.checkDados());
		}

		[HttpPost]
		public ActionResult createDatabase(string password_migration) {
			string chk = checkAuth(password_migration);

			if (chk == "") {
				return Json(MigrationsModel.createDatabase());
			} else {
				return Json(new { msg_erro = chk });
			}
		}

		[HttpPost]
		public ActionResult UpdateTables(string password_migration) {
			string chk = checkAuth(password_migration);

			if (chk == "") {
				return Json(MigrationsModel.UpdateTables());
			} else {
				return Json(new { msg_erro = chk });
			}
		}

		[HttpPost]
		public ActionResult dropDatabase(string password_migration) {
			string chk = checkAuth(password_migration);

			if (chk == "") {
				return Json(MigrationsModel.DropDatabase());
			} else {
				return Json(new { msg_erro = chk });
			}
		}

		[HttpPost]
		public ActionResult dropTables(string password_migration) {
			string chk = checkAuth(password_migration);

			if (chk == "") {
				return Json(MigrationsModel.DropTables());
			} else {
				return Json(new { msg_erro = chk });
			}
		}

		


	}
}

GerenciamentoCinema/Views/Home/Home.cshtml
@*@model GerenciamentoCinema.Models.LoginViewModel*@

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Home Page</h2>
<h3>Bem vindo @Session["auth_user_name"] </h3>

GerenciamentoCinema/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>GERENCIAMENTO DE CINEMA</h1>
    <p class="lead">Gerencie suas salas de cinema como nunca.</p>
    @Html.ActionLink("Faça login", "Login", "Home", null, new { @class = "btn btn-primary btn-lg" })

</div>

<div class="row">
    <div class="col-md-4">
        <h2>Primeiro passos</h2>
        <p> Para iniciar o gerenciamento do seu cinema, primeiro precisamos preparar o seu ambiente, basta acessar o link abaixo,preencher a senha e clique em 'criar database'</p>
        @Html.ActionLink("Acesse agora", "Index", "Migrations", null, new { @class = "btn btn-default" })
    </div>
    <div class="col-md-4">
        <h2>Atualizando o sistema</h2>
        <p> Para finalizar o ambiente, basta acessar o link abaixo,preencher a senha e clique em  'atualizar database'</p> 
        @Html.ActionLink("Acesse agora", "Index", "Migrations", null, new { @class = "btn btn-default" })
    </div>
    <div class="col-md-4">
        <h2>Iniciando</h2>
        <p>Começe agora mesmo gerenciando seus filmes,salas e sessões</p>
       @Html.ActionLink("Faça Login", "Login", "Home", null, new { @class = "btn btn-default" })
    </div>
</div>

GerenciamentoCinema/Views/Home/Login.cshtml
@model GerenciamentoCinema.Models.UserModel

<div class="container wrp">
    <div class="row">
        <h3> @ViewBag.title </h3>
    </div>

    <div class="row">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "home", null, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group ">
                    @Html.LabelFor(m => m.user, new { })

                    @Html.TextBoxFor(m => m.user, new { @class = "form-control", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.user, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.password, new { })

                    @Html.PasswordFor(m => m.password, new { @class = "form-control", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.password, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    <input type="submit" id="btn_submit" class="btn btn-success col-md-12" value="login" />
                </div>

                <div id="erroDiv" class="form-group alert alert-danger" role="alert" hidden>
                    <p class="p-3 mb-2 bg-danger text-white" id="resultErro"></p>
                </div>
                <div id="erroDiv1" class="form-group alert alert-danger" role="alert" hidden>
                    @Html.ActionLink("Acesse agora", "Index", "Migrations", null, new { @class = "btn btn-danger" })
                </div>}

        </section>
    </div>
</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(function () {
        $.ajax({
            url: "/Migrations/check",
            type: 'POST',
            contentType: "application/json",
            dataType: 'json',

            success: function (result) {
                console.log(result);

                if (!result.status) {
                    $('#erroDiv').show();
                    $('#erroDiv1').show();
                    $('#user').prop('disabled', true);
                    $('#password').prop('disabled', true);
                    $('#btn_submit').prop('disabled', true);
                    $('#resultErro').text("Erro estrutural, verifique database e tabelas");
                } else if (result.msg_erro != "") {
                    $('#erroDiv').show();

                    $('#btn_submit').prop('disabled', true);
                    $('#resultErro').text(result.msg_erro);
                } else {
                    $('#erroDiv').hide();
                }


            },
            error: function (result) {
                $('#resultErro').text(result.msg_erro);
                $('#erroDiv').Show();
            }
        });
    });


</script>