GerenciamentoCinema/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GerenciamentoCinema.Controllers
{
    public class ConfigController : Controller
    {
        // GET: Config
        public ActionResult Index()
        {
            if (GeneralController.isAuth())
            {
                ViewBag.Title = "Configurações do sistema";
                return View();
            }
            else
            {
                return RedirectToAction("deny", "Access");
            }
        }

        [HttpPost]
        public JsonResult Save(ConfigModel config)
        {
            return Json(ConfigModel.Save(config));
        }

        [HttpPost]
        public JsonResult Load()
        {
            return Json(ConfigModel.Load());
        }



        public static int getTempoLimpeza()
        {
            return ConfigModel.getTempoLimpeza();
        }

    }
}

GerenciamentoCinema/Controllers/FilmeController.cs
using GerenciamentoCinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using GerenciamentoCinema.Controllers;
using System.Web.Script.Serialization;
using System.Web.UI.WebControls;
using System.IO;

namespace GerenciamentoCinema.Controllers {


	public class FilmeController : Controller {

		public const string tablename = "filmes";
		public ActionResult Index() {
			if (GeneralController.isAuth()) {
				ViewBag.Title = "Cadastros de filmes";
				var result = GeneralModel.getTotalPaginas(tablename, " where deleted = 0");
				ViewBag.TotPag = result.Item1;
				ViewBag.TotReg = result.Item2;
				ViewBag.RegPorPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = 1;
				return View("Index");
			} else {
				return RedirectToAction("deny", "Access");
			}
		}

		[HttpPost]
		public JsonResult IndexPG(int pg, string busca, string filtro_status = "") {
			if (GeneralController.isAuth()) {
				switch (filtro_status) {
					case "emcartaz":
						filtro_status = "AND em_cartaz = 1 ";
						break; //somente filmes em cartaz
					case "foracartaz":
						filtro_status = "AND em_cartaz = 0";
						break; //somente filmes fora de cartaz
					default:
						filtro_status = " AND 1=1 ";
						break; //Sem restrição de filtro

				};

				var list = FilmeModel.listLimmit(pg, busca, filtro_status);
				ViewBag.MaxPPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = pg;
				return Json(list);
			} else {
				return null;
			}
		}

		[HttpPost]
		public JsonResult ListEmCartaz(int pg, string busca) {
			if (GeneralController.isAuth()) {
				var list = FilmeModel.listLimmit(pg, busca, " AND em_cartaz = 1");
				ViewBag.MaxPPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = pg;
				return Json(list);
			} else {
				return null;
			}
		}


		public ActionResult Novo() {
			if (GeneralController.isAuth()) {
				ViewBag.Title = "Novo filme";
				return View("Novo");
			} else {
				return RedirectToAction("deny", "Access");
			}
		}

		[HttpPost]
		public ActionResult Novo(FilmeModel filme) {
			ViewBag.Title = "Novo filme";
			if (!ModelState.IsValid) {
				return View(filme);
			} else {
				var result = FilmeModel.Insert(filme);
				if (result == "") {
					var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "success", "Filme incluido com sucesso");
					TempData["html_last_index"] = resultToast.Item1;
					TempData["html" + resultToast.Item1] = resultToast.Item2;
					return RedirectToAction("Index");
				} else {
					var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "warning", result);
					TempData["html_last_index"] = resultToast.Item1;
					TempData["html" + resultToast.Item1] = resultToast.Item2;
					ModelState.Clear();
					return View(filme);
				}
			}
		}

		public ActionResult Editar(int id) {
			ViewBag.Title = "Editar filme " + id.ToString();
			if (GeneralController.isAuth()) {
				FilmeModel a = FilmeModel.locateByID(id);
				if (a.id <= 0) {// não achou o filme
					var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "warning", "Filme não localizado");
					TempData["html_last_index"] = resultToast.Item1;
					TempData["html" + resultToast.Item1] = resultToast.Item2;
					return RedirectToAction("Index");
				} else {
					return View(a);
				}

			} else {
				return RedirectToAction("deny", "Access");
			}
		}

		[HttpPost]
		public JsonResult Visualizar(int id) {
			if (GeneralController.isAuth()) {
				FilmeModel a = FilmeModel.locateByID(id);
				if (a.id <= 0) {// não achou o filme
					return Json(new { msg = "Filme não localizado" });
				} else {
					return Json(a);
				}

			} else {
				return null;
			}
		}

		[HttpPost]
		public ActionResult Editar(FilmeModel filme) {
			ViewBag.Title = "Editar filme";
			if (!ModelState.IsValid) {
				return View(filme);
			} else {
				var result = FilmeModel.Update(filme);
				if (result == "") {
					var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "success", "Filme editado com sucesso");
					TempData["html_last_index"] = resultToast.Item1;
					TempData["html" + resultToast.Item1] = resultToast.Item2;

					return RedirectToAction("Index");
				} else {
					var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "warning", result);
					TempData["html_last_index"] = resultToast.Item1;
					TempData["html" + resultToast.Item1] = resultToast.Item2;

					return View(filme);
				}
			}
		}

		[HttpPost]
		public JsonResult canDelete(int id) {
			return Json(FilmeModel.canDelete(id));
		}

		[HttpPost]
		public JsonResult deletar(int id) {
			var result = FilmeModel.delete(id);
			if (result == "") {
				var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "success", "Filme deletado com sucesso");
				TempData["html_last_index"] = resultToast.Item1;
				TempData["html" + resultToast.Item1] = resultToast.Item2;
				return Json(new { msg = result });
			} else {
				var resultToast = GeneralController.sendToast(TempData["html_last_index"] == null ? -1 : (int)TempData["html_last_index"], "error", result);
				TempData["html_last_index"] = resultToast.Item1;
				TempData["html" + resultToast.Item1] = resultToast.Item2;
				return Json(new { msg = result });
			}
		}

		[HttpPost]
		public JsonResult locateIDByTitulo(string name) {
			int filme_id = FilmeModel.locateIDByTitulo(name);
			return Json(new { filme_id });
		}

		[HttpPost]
		public JsonResult HardDelete() {
			Boolean deleted_all = FilmeModel.HardDelete();
			return Json(new { deleted_all });
		}


	}
}

GerenciamentoCinema/Controllers/SalaController.cs
using GerenciamentoCinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GerenciamentoCinema.Controllers
{
    public class SalaController : Controller
    {
		public const string tablename = "salas";
		public ActionResult Index() {
			if (GeneralController.isAuth()) {
				ViewBag.Title = "Cadastros de salas";
				var result = GeneralModel.getTotalPaginas(tablename);
				ViewBag.TotPag = result.Item1;
				ViewBag.TotReg = result.Item2;
				ViewBag.RegPorPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = 1;
				return View();
			} else {
				return RedirectToAction("deny", "Access");
			}
		}

		[HttpPost]
		public JsonResult IndexPG(int pg) {
			if (GeneralController.isAuth()) {
				var list = SalaModel.listLimmit(pg);
				ViewBag.MaxPPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = pg;
				return Json(list);
			} else {
				return null;
			}
		}

		[HttpPost]
		public JsonResult list() {
			if (GeneralController.isAuth()) {
				var list = SalaModel.list();
				return Json(list);
			} else {
				return null;
			}
		}

	}
}

GerenciamentoCinema/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GerenciamentoCinema.Models;

namespace GerenciamentoCinema.Controllers {
	public class UserController : Controller {
		public const string tablename = "usuarios";

		public ActionResult Index() {
			if (GeneralController.isAuth()) {
				ViewBag.Title = "Cadastros de usuários";
				var result = GeneralModel.getTotalPaginas(tablename);
				ViewBag.TotPag = result.Item1;
				ViewBag.TotReg = result.Item2;
				ViewBag.RegPorPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = 1;
				return View();
			} else {
				return RedirectToAction("deny", "Access");
			}
		}

		[HttpPost]
		public JsonResult IndexPG(int pg) {
			if (GeneralController.isAuth()) {
				var list = UserModel.listLimmit(pg);
				ViewBag.MaxPPag = GeneralController.MaxPPag;
				ViewBag.PagAtual = pg;
				return Json(list);
			} else {
				return null;
			}
		}

	}
}

GerenciamentoCinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema para controle de cinemas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema para controle de cinemas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @if (Convert.ToBoolean(Session["auth"])) {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Filmes", "Index", "Filme")</li>
                        <li>@Html.ActionLink("Salas", "Index", "Sala")</li>
                        <li>@Html.ActionLink("Sessões", "Index", "Sessao")</li>
                        <li>@Html.ActionLink("Usuários", "Index", "User")</li>
                        <li>@Html.ActionLink("Configurações", "Index", "Config")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li> <a class="noHover"> Olá @Session["auth_user_name"] </a>  </li>
                        <li>@Html.ActionLink("Sair", "LogOff", "Home")</li>
                    </ul>} else {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    </ul>}

            </div>
        </div>
    </div>



    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema para controle de cinemas</p>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-TimePicker-1.0.0.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    @RenderSection("scripts", required: false)



    @{int i = 0;
        do {
            @Html.Raw(TempData["html" + i.ToString()]);
            i++;
        } while (TempData["html" + i.ToString()] != null);
        TempData.Clear();
    }

</body>
</html>